package com.enzo.yxzapp.enums;

public enum TipoOficina {
    STORY_STARTER,
    MAKER_ROBOTICA_O_QUE_E_PAEBM_8ANO_AO_3SERIE_EM,
    ROBOTICA_LOGISTICA_VALE_6ANO_AO_SUPERIOR,
    ROBOTICA_PELOTIZACAO_VALE_6ANO_AO_SUPERIOR,
    ROBOTICA_MINERACAO_VALE_6ANO_AO_SUPERIOR

}
